import { createContext, useMemo } from "react";
import useLocalMedia from "../hooks/useLocalMedia";

const LocalMediaContext = createContext({
  permissions: undefined,
  localVideoMounted: undefined,
  localAudioMounted: undefined,
  audioDevices: undefined,
  videoDevices: undefined,
  localAudioStreamRef: undefined,
  localVideoStreamRef: undefined,
  localVirtualVideoStreamRef: undefined,
  localVirtualVideoStageStreamRef: undefined,
  localAudioDeviceId: undefined,
  localVideoDeviceId: undefined,
  localStageAudioStreamRef: undefined,
  localStageVideoStreamRef: undefined,
  localStageScreenShareStreamRef: undefined,
  localAudioDeviceError: undefined,
  localVideoDeviceError: undefined,
  videoElemRef: undefined,
  refreshSceneRef: undefined,
  whiteboardCanvasRef: undefined,
  localScreenShareStreamRef: undefined,
  updateLocalAudio: undefined,
  updateLocalVideo: undefined,
  setInitialDevices: undefined,
  refreshDevices: undefined,
  setAudioDevices: undefined,
  setVideoDevices: undefined,
  startScreenShare: undefined,
  stopScreenShare: undefined,
  initiateCanvasStream: undefined,
});

function LocalMediaProvider({ children }) {
  const {
    permissions,
    localVideoMounted,
    localAudioMounted,
    audioDevices,
    videoDevices,
    localAudioStreamRef,
    localVideoStreamRef,
    localAudioDeviceId,
    localVideoDeviceId,
    localStageAudioStreamRef,
    localStageVideoStreamRef,
    localVirtualVideoStreamRef,
    localVirtualVideoStageStreamRef,
    videoElemRef,
    canvasElemRef,
    refreshSceneRef,
    whiteboardCanvasRef,
    localScreenShareStreamRef,
    localStageScreenShareStreamRef,
    localAudioDeviceError,
    localVideoDeviceError,
    updateLocalAudio,
    updateLocalVideo,
    setInitialDevices,
    cleanUpDevices,
    refreshDevices,
    setAudioDevices,
    setVideoDevices,
    startScreenShare,
    stopScreenShare,
    initiateCanvasStream,
  } = useLocalMedia();

  const state = useMemo(() => {
    return {
      permissions,
      localVideoMounted,
      localAudioMounted,
      audioDevices,
      videoDevices,
      localAudioStreamRef,
      localVideoStreamRef,
      localVirtualVideoStreamRef,
      localVirtualVideoStageStreamRef,
      localAudioDeviceId,
      localVideoDeviceId,
      localStageAudioStreamRef,
      localStageVideoStreamRef,
      videoElemRef,
      refreshSceneRef,
      whiteboardCanvasRef,
      localScreenShareStreamRef,
      localStageScreenShareStreamRef,
      localAudioDeviceError,
      localVideoDeviceError,
      updateLocalAudio,
      updateLocalVideo,
      setInitialDevices,
      cleanUpDevices,
      refreshDevices,
      setAudioDevices,
      setVideoDevices,
      startScreenShare,
      stopScreenShare,
      initiateCanvasStream,
    };
  }, [
    permissions,
    localVideoMounted,
    localAudioMounted,
    audioDevices,
    videoDevices,
    localAudioStreamRef,
    localVideoStreamRef,
    localVirtualVideoStreamRef,
    localVirtualVideoStageStreamRef,
    localAudioDeviceId,
    localVideoDeviceId,
    localStageAudioStreamRef,
    localStageVideoStreamRef,
    videoElemRef,
    canvasElemRef,
    refreshSceneRef,
    whiteboardCanvasRef,
    localScreenShareStreamRef,
    localStageScreenShareStreamRef,
    localAudioDeviceError,
    localVideoDeviceError,
    updateLocalAudio,
    updateLocalVideo,
    setInitialDevices,
    cleanUpDevices,
    refreshDevices,
    setAudioDevices,
    setVideoDevices,
    startScreenShare,
    stopScreenShare,
    initiateCanvasStream,
  ]);

  return (
    <LocalMediaContext.Provider value={state}>
      {children}
    </LocalMediaContext.Provider>
  );
}

export default LocalMediaProvider;
export { LocalMediaContext };
